### ISSUE TITLE
Zwift Trainer Dificulty 

### ISSUE THREAD

**Issue by acwalter** [Berg0162/simcline#10]
Zwift trainer difficulty, by default set to 50%, causes Zwift to send the grade *.5 so the simcline only receives 1/2 the actual grade. Do others experience this? My quick fix is to set the GradeChangeFactor to 200. 

If this is they way Zwift works, I though I would use the .aia file in the MIT app builder and update the incline slider to allow values from 0-200, maybe even 400 if someone were to use Zwift at 25% trainer dificulty, instead of 0-100. The only trouble I am having is getting the apk to run on my phone. If I import a project and use the latest 2.5.1.aia file, and then generate an apk without changing anything I get an error when connecting to the simcline. Anyone know if there is something additional I need to do other than import the .aia file?

**Comment by Berg0162** [comment]
Dear Walter,
>Zwift trainer difficulty, by default set to 50%, causes Zwift to send the grade *.5 so the simcline omly receives 1/2 the actual grade. Do others experience this? My quick fix is to set the GradeChangeFactor to 200.<br>

The trainer calculates the resistance, among others using the road grade information. That's why Zwift sends modified road grades to the trainer, dependent of the difficulty setting. Just for the record, when you change the Zwift difficulty setting from 50% to 100%, Zwift will send genuine (i.e. unmodified) grades to the trainer (WYSIWYG) and as a consequence the Simcline will lift accordingly! That is really a quick fix! The Zwifters I know, have all the Zwift difficulty setting at 100%, because they want a "road-realistic" experience when training and racing indoors with Zwift.<br>

The GradeChangeFactor functionality was originally designed and implemented to allow the Simcline user to attenuate the actuator movements not the opposite! Feel free to modify the code to whatever conforms your preferences.<br>

>and then generate an apk wothout chabging anything I get an error when connecting to the simcline<br>

It would help when you document the error state that you encounter....

**Comment by Berg0162** [comment]
Issue seems to be fixed!

**Comment by acwalter** [comment]
I finally had time to look into this and found the issue with the BLE extension causing crashes on my version of Android. It has a patch https://iot.appinventor.mit.edu/iot/reference/bluetoothle
